### ISSUE TITLE
Does WasmEdge support the GPU version TensorFlow C library?

### ISSUE THREAD

**Issue by FENP** [second-state/WasmEdge-tensorflow-deps#2]
I want to use GPU to speed up model inference. But only the CPU version seems to be available here, and TensorFlow models only run on the CPU. Does WasmEdge support the GPU version TensorFlow? 
Thanks for any suggestions.

**Comment by hydai** [comment]
You can replace the CPU one with GPU one. The deps is using CPU, because this deps repo is only for general purpose legacy systems.

**Comment by FENP** [comment]
> You can replace the CPU one with GPU one. The deps is using CPU, because this deps repo is only for general purpose legacy systems.

Thanks for your suggestion, it works!
