### ISSUE TITLE
Build Fail on Mac M1 chip

### ISSUE THREAD

**Issue by Hrushi20** [second-state/WasmEdge-tensorflow-deps#7]
I'm not able to build this project on my Mac M1 chip. I followed the exact steps in the README.md.

<img width="1431" alt="Screenshot 2023-08-02 at 3 06 37 PM" src="https://github.com/second-state/WasmEdge-tensorflow-deps/assets/65367566/1d651e59-ba0b-44f9-b25a-12044cbad2e3">

<img width="1431" alt="Screenshot 2023-08-02 at 3 10 11 PM" src="https://github.com/second-state/WasmEdge-tensorflow-deps/assets/65367566/8832f6f5-668b-415a-9e94-005bbc2dfb4a">

**Comment by Hrushi20** [comment]
@juntao , @hydai

**Comment by hydai** [comment]
I cannot reproduce your issue on my apple silicon model MacBook. Please make sure the commands are using the same as the documents.

**Comment by Hrushi20** [comment]
My bad, I had two different versions of python installed. It took a lot of time to build from the source files. Thanks for helping me out :)
